language: php
php:
  - "5.4"
  - "5.5"
  - "hhvm"

before_script:
  - curl -s https://getcomposer.org/installer | php && php composer.phar update --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml -c SilMock/tests/phpunit.xml SilMock/tests/
  
after_script:
  - php vendor/bin/coveralls -v
