version: '2.2'
services:
    cli:
        build: ./
        volumes:
            - ./:/vagrant
        working_dir: /vagrant
        command: ["true"]

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.35.0/24
              gateway: 10.20.35.1
