#version tag is obsolete
services:
    cli:
        build: ./
        volumes:
            - ./:/data
        working_dir: /data
        command: ["true"]

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.35.0/24
              gateway: 10.20.35.1
