name: PHPUnit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@run-as-current-user

      - name: PHPUnit Tests
        uses: php-actions/phpunit@composer-version--user
        working-directory: /data/SilMock/tests
        with:
          bootstrap: vendor/autoload.php
          configuration: /data/SilMock/tests/phpunit.xml
